// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSkill struct {
	ID               pgtype.UUID
	Name             string
	YoutubeVideoID   string
	IsVideoLandscape bool
	Level            int16
	Categories       []string
	Prerequisites    []pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
